# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # Workflow inputs given to nextflow.
    # The workflow should define `--out_dir`, the CI template sets this.
    # Only common file inputs and option values need to be given here
    # (not things such as -profile)
    NF_WORKFLOW_OPTS: "--fastq test_data/fastq --sample_sheet test_data/sample_sheet.csv"
    NF_IGNORE_PROCESSES: "downSample"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_NAME: "wf-tb-amr-v1"
    PYTEST_CONTAINER_CONFIG_KEY: "container_sha="
# pytest:
#     image: ubuntu:20.04
#     stage: preflight
#     script:
#        - apt update -qq && apt install -y -qq python3-venv python3-pip python-is-python3
#         - make test
#         - python -m venv pytest
#         - . pytest/bin/activate
#         - pip install --upgrade pip
#         - pip install wheel
#         - pip install pytest pyyaml
#         - pip install -r requirements.txt
#         - pytest
